import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")
ELASTICSEARCH_LOCAL_USERNAME = 'elastic'
ELASTICSEARCH_LOCAL_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD")
ELASTICSEARCH_SERVICE = 'bonsai'
ELASTICSEARCH_BONSAI_URL = os.getenv("ELASTICSEARCH_BONSAI_URL")
ELASTICSEARCH_LOCAL_URL = 'http://localhost:9200'

DEBUG = True
ENHANCED_DEBUG = False